--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game:GetService("Players");local v1=v0.LocalPlayer;local v2=game:GetService("RunService");local v3=game:GetService("UserInputService");local v4=workspace.CurrentCamera;local v5=Instance.new("ScreenGui",v1:WaitForChild("PlayerGui"));v5.Name="ShotHub🤫";v5.ResetOnSpawn=false;local v8=Instance.new("Frame",v5);v8.Size=UDim2.new(0,160,0,60);v8.Position=UDim2.new(0.5, -80,0.1,0);v8.BackgroundColor3=Color3.fromRGB(30,30,30);v8.Active=true;v8.Draggable=true;v8.BorderSizePixel=0;Instance.new("UICorner",v8).CornerRadius=UDim.new(0,12);local v16=Instance.new("UIStroke",v8);v16.Thickness=2;v16.LineJoinMode=Enum.LineJoinMode.Round;task.spawn(function() while task.wait() do local v44=tick() * 3 ;local v45=(math.sin(v44) * 127) + 128 ;local v46=(math.sin(v44 + 2 ) * 127) + 128 ;local v47=(math.sin(v44 + 4 ) * 127) + 128 ;v16.Color=Color3.fromRGB(v45,v46,v47);end end);local v20=Instance.new("TextButton",v8);v20.Size=UDim2.new(1, -10,0.45, -5);v20.Position=UDim2.new(0,5,0,5);v20.BackgroundColor3=Color3.fromRGB(50,50,50);v20.Text="🔲 Hitbox";v20.TextColor3=Color3.new(1,1,1);v20.Font=Enum.Font.GothamBold;v20.TextScaled=true;Instance.new("UICorner",v20);local v29=Instance.new("TextButton",v8);v29.Size=UDim2.new(1, -10,0.45, -5);v29.Position=UDim2.new(0,5,0.5,5);v29.BackgroundColor3=Color3.fromRGB(50,50,50);v29.Text="🎯 Auto Bắn";v29.TextColor3=Color3.new(1,1,1);v29.Font=Enum.Font.GothamBold;v29.TextScaled=true;Instance.new("UICorner",v29);local v37=false;local v38=false;local function v39() for v49,v50 in pairs(v0:GetPlayers()) do if ((v50~=v1) and v50.Character and v50.Character:FindFirstChild("HumanoidRootPart")) then local v55=v50.Character.HumanoidRootPart;v55.Size=Vector3.new(50,50,50);v55.Transparency=0.5;v55.Material=Enum.Material.Neon;v55.Color=Color3.fromRGB(255,0,0);v55.CanCollide=false;end end end local v40={};local function v41() for v51,v52 in pairs(v0:GetPlayers()) do if ((v52~=v1) and v52.Character and v52.Character:FindFirstChild("HumanoidRootPart")) then local v62=v52.Character.HumanoidRootPart;local v63,v64=v4:WorldToViewportPoint(v62.Position);if (v64 and  not v40[v52]) then mouse1click();v40[v52]=true;end end end end v20.MouseButton1Click:Connect(function() v37= not v37;v20.Text=(v37 and "✅ Hitbox") or "🔲 Hitbox" ;end);v29.MouseButton1Click:Connect(function() v38= not v38;v29.Text=(v38 and "✅ Auto Bắn") or "🎯 Auto Bắn" ;end);v2.RenderStepped:Connect(function() if v37 then v39();end if v38 then v41();end end);if ( not isexecutorclosure or  not mouse1click) then getgenv().mouse1click=function() local v54=game:GetService("VirtualInputManager");v54:SendMouseButtonEvent(0,0,0,true,game,0);v54:SendMouseButtonEvent(0,0,0,false,game,0);end;end
